actions/urls.py
from django.contrib.auth.decorators import login_required
from django.urls import path

actions_urlpatterns = []

applyIdscea/urls.py
from django.contrib import admin
from django.urls import path
from django.views.generic import TemplateView

from accounts.urls import accounts_urlpatterns
from profile.urls import profile_urlpatterns
from dashboard.urls import dashboard_urlpatterns
from reviews.urls import reviews_urlpatterns
from actions.urls import actions_urlpatterns
from programs.urls import programs_urlpatterns
from applications.urls import applications_urlpatterns
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path(r"", TemplateView.as_view(template_name="home.html"), name="home"),
    path("admin/", admin.site.urls),
]

urlpatterns += (accounts_urlpatterns
                + profile_urlpatterns
                + programs_urlpatterns
                + applications_urlpatterns
                + dashboard_urlpatterns
                + actions_urlpatterns
                + reviews_urlpatterns
                )

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

reviews/urls.py
from django.contrib.auth.decorators import login_required
from django.urls import path

from reviews.views import *

reviews_urlpatterns = [
    path(
        "staff/applications",
        login_required(ApplicationsListView.as_view()),
        name="staff-applications-list",
    ),
    path(
        "staff/awards",
        login_required(AwardsListView.as_view()),
        name="staff-awards-list",
    ),
    path(
        "staff/pendingtasks",
        login_required(PendingTasksListView.as_view()),
        name="staff-pending-tasks-list",
    ),
    path(
        "staff/pendingtasks/<pk>",
        login_required(complete_pending_tasks),
        name="staff-pending-tasks-detail",
    ),
    path(
        "staff/applications/<pk>",
        login_required(ApplicationDetailReview.as_view()),
        name="staff-application-review",
    ),
    path(
        "staff/applications/<pk>/validate",
        login_required(validate_application),
        name="staff-application-review-validate",
    ),
    path(
        "staff/applications/<pk>/comment",
        login_required(comment_application),
        name="staff-application-review-comment",
    ),
    path(
        "staff/awards/<pk>/deliver",
        login_required(deliver_award),
        name="staff-deliver-award",
    ),
    path(
        "staff/awards/<pk>/validate",
        login_required(validate_deliverable),
        name="staff-validate-deliverable",
    ),
    path(
        "staff/application/<pk>/award/redirect",
        login_required(ApplicationAwardRedirect.as_view()),
        name="staff-application-award-redirect",
    ),
    path(
        "staff/application/<pk>/award/create",
        login_required(ApplicationAwardCreate.as_view()),
        name="staff-application-award-create",
    ),
    path(
        "staff/application/<pk>/award/update",
        login_required(ApplicationAwardUpdate.as_view()),
        name="staff-application-award-update",
    ),
]

applications/models.py
import os
from uuid import uuid4

from django.conf import settings
from django.db import models

from programs.models import Program


class Application(models.Model):
    APPLICATION_STAGES = (
        (0, "Pendiente"),
        (1, "Enviada"),
        (2, "Resolver observaciones"),
        (3, "Validada"),
        (4, "Decisión final"),
        (5, "Seguimiento"),
        (6, "Concluida"),
        (-1, "Cancelada"),
    )

    username = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        verbose_name="Solicitante",
    )
    program = models.ForeignKey(
        to=Program,
        on_delete=models.CASCADE,
        verbose_name="Programa",
    )
    folio = models.CharField("Folio", unique=True, max_length=256)
    current_stage = models.IntegerField(
        "Estatus",
        choices=APPLICATION_STAGES,
        default=0,
    )
    score = models.CharField("Puntuación", max_length=64, null=True, blank=True)
    validated = models.BooleanField(default=False)
    comments = models.TextField("Comentarios", null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        unique_together = (
            (
                "program",
                "username",
            ),
        )

    def __str__(self):
        return "%s - %s - %s" % (self.program, self.folio, self.username)


def path_and_rename(instance, filename):
    upload_to = "deliverables"
    ext = filename.split(".")[-1]
    filename = "{}.{}".format(instance.username.username, ext)
    return os.path.join(upload_to, filename)


class Award(models.Model):
    AWARD_STATUS = ((0, "Rechazado"), (1, "Aprobado"))

    id = models.OneToOneField(
        Application,
        on_delete=models.CASCADE,
        primary_key=True,
    )

    username = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        verbose_name="Solicitante",
    )
    program = models.ForeignKey(
        to=Program,
        on_delete=models.CASCADE,
        verbose_name="Programa",
    )
    decision = models.IntegerField(
        "Decisión",
        choices=AWARD_STATUS,
        null=True,
    )
    awarded = models.IntegerField("Monto autorizado", default=0, null=True, blank=True)
    comments = models.TextField("Comentarios", null=True, blank=True)
    acta = models.CharField("Número de acta", null=True, blank=True, max_length=100)
    require_deliverable = models.BooleanField("Requiere entregables", default=False)
    deliverable_by = models.DateTimeField("Fecha para entregables", null=True, blank=True)
    deliverable = models.FileField("Entregable", null=True, blank=True, upload_to=path_and_rename)
    deliverable_validated = models.BooleanField("Entregable validado", default=False)
    award_delivered = models.BooleanField("Apoyo entregado", default=False)
    award_delivered_at = models.DateTimeField("Fecha de entrega de apoyo", null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return "%s - %s" % (self.program, self.username)


class ApplicationContentConvocatoria(models.Model):
    LANGUAGES = (
        ("Español", "Español"),
        ("Inglés", "Inglés"),
        ("Portugués", "Portugués"),
        ("Francés", "Francés"),
        ("Otro", "Otro"),
    )

    id = models.OneToOneField(
        Application,
        on_delete=models.CASCADE,
        primary_key=True,
    )
    date_start = models.DateField(verbose_name="Fecha de inicio del programa")
    date_end = models.DateField(verbose_name="Fecha de término del programa")
    project_name = models.CharField(
        verbose_name="Nombre del proyecto de investigación o de estudios", max_length=120
    )
    description = models.TextField(
        verbose_name="Descripción del proyecto de investigación o estudios"
    )
    program_name = models.CharField(
        verbose_name="Nombre del programa de estudios", max_length=120
    )
    objective = models.TextField(
        "Objetivo del programa de estudios"
    )
    credits = models.IntegerField("Número de asignaturas o créditos del programa")
    duration_hours = models.IntegerField("Duración del programa de estudios (horas)")
    language = models.CharField(
        "Idioma en que se imparte el programa",
        choices=LANGUAGES,
        max_length=50,
    )
    area = models.CharField("Área o disciplina en la que se realizarán los estudios", max_length=100)
    impact = models.TextField("Impacto y beneficios del programa de estudios para el estado")
    institution = models.CharField(
        "Institución donde realizará sus estudios o actividad", max_length=100
    )
    location = models.CharField(
        "Ciudad o país donde realizará sus estudios o actividad", max_length=100
    )
    materias = models.TextField(
        "Lista de materias y número de créditos",
        help_text="Sólo en caso de estar matriculado y cursando un programa de doctorado o maestría. Inserte una materia por renglon con el número de créditos separado con una coma, por ejemplo:<br/>Matemáticas, 4<br/>Español, 4<br/>Ciencias Naturales, 6",
        null=True,
        blank=True,
    )
    research_topic = models.CharField(
        "Línea de investigación",
        max_length=400,
        help_text="Solo en caso de estar matriculado y cursando programa de doctorado o maestría.",
        null=True,
        blank=True,
    )
    program_requirements = models.CharField(
        "Link al programa de estudios",
        max_length=400,
        help_text="Enlace o link o nombre del documento donde se pueda verificar la información de la estructura curricular y las líneas de investigación. Si la información se encuentra en un documento entregado en su expediente, indicar los números de página en donde se ubica.",
    )

    total_movilidad = models.IntegerField("Costo total - Movilidad", default=0)
    requested_movilidad = models.IntegerField("Solicitado - Movilidad", default=0)
    total_investigacion = models.IntegerField("Costo total - Investigación", default=0)
    requested_investigacion = models.IntegerField(
        "Solicitado - Investigación", default=0
    )
    total_inscripcion = models.IntegerField("Costo total - Inscripción", default=0)
    requested_inscripcion = models.IntegerField("Solicitado - Inscripción", default=0)
    total_viaticos = models.IntegerField("Costo total - Colegiatura", default=0)
    requested_viaticos = models.IntegerField("Solicitado - Colegiatura", default=0)
    total_otros = models.IntegerField("Costo total - Otros", default=0)
    requested_otros = models.IntegerField("Solicitado - Otros", default=0)

    personal_statement = models.TextField(
        "Objetivo personal que lo impulsó para seguir estudiando"
    )
    suitability = models.TextField(
        "Explique, ¿por qué es pertinente el apoyar su formación en la modalidad pretendida?"
    )
    future_plans = models.TextField(
        "Planes de trabajo después de terminar sus estudios"
    )
    importance = models.TextField(
        "Fundamente las ventajas de esta institución y programa sobre la oferta educativa en Aguascalientes"
    )
    statement_of_purpose = models.TextField(
        "Exposición de motivos",
        default="Me dirijo a usted de la manera más atenta para solicitarle...\n\nObjetivo...\n\nMotivo de solicitud...\n\nBeneficios e impacto que tendrá realizar sus estudios o actividad para la cual requiere el apoyo...\n",
    )
    program_relation_cti = models.TextField(
        "Señale la relación del proyecto de estudios con los sectores estratégicos y el impacto o beneficios para el Estado"
    )
    program_relation_state = models.TextField(
        "Argumetación sobre la relación del proyecto o programa de estudios con la ciencia, la tecnología y la innovación"
    )

    current_job = models.CharField(
        "Institución o empresa donde estudia o trabaja actualmente",
        max_length=400,
    )
    last_academic_grade = models.CharField(
        "Último grado académico o módulo cursado",
        max_length = 200,
    )
    last_grade = models.CharField(
        "Promedio último obtenido / equivalencia",
        max_length=50,
        help_text="Anexar documento oficial institucional si corresponde al extranjero, solo aplica para modalidad de becas por convocatoria."
    )

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def get_fields(self):
        omit = ("id",)
        return [
            (field.name, field.verbose_name, field.value_to_string(self))
            for field in ApplicationContentConvocatoria._meta.fields
            if field.name not in omit
        ]

    def __str__(self):
        return "%s - %s - %s" % (self.id, self.id.username, self.id.program)


class ApplicationContentApoyo(models.Model):

    LANGUAGES = (
        ("Español", "Español"),
        ("Inglés", "Inglés"),
        ("Portugués", "Portugués"),
        ("Francés", "Francés"),
        ("Otro", "Otro"),
    )

    id = models.OneToOneField(
        Application,
        on_delete=models.CASCADE,
        primary_key=True,
    )
    date_start = models.DateField(verbose_name="Fecha de inicio del programa")
    date_end = models.DateField(verbose_name="Fecha de término del programa")
    name = models.CharField(
        verbose_name="Nombre del programa de estudios", max_length=120
    )
    description = models.TextField(
        verbose_name="Descripción del programa, tema de estudio o actividad académica que pretende realizar"
    )
    objective = models.TextField(
        "Objetivo de los estudios o actividad que realizará y para la cuál pide el apoyo"
    )
    credits = models.IntegerField("Número de asignaturas o créditos del programa")
    duration_hours = models.IntegerField("Duración del programa de estudios (horas)")
    language = models.CharField(

reviews/models.py
from django.conf import settings
from django.db import models

from programs.models import Program


class ReviewersProgramACL(models.Model):
    username = models.ForeignKey(
        to=settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
    )
    program = models.ForeignKey(
        to=Program,
        on_delete=models.CASCADE,
    )

    def __str__(self):
        return "Username: %s - Program: %s" % (
            self.username,
            self.program.application_prefix,
        )

reviews/forms.py
from datetime import datetime

from applications.models import Award
from profile.models import *

from crispy_forms.bootstrap import Field, FormActions
from crispy_forms.helper import FormHelper
from crispy_forms.layout import HTML, Column, Layout, Row, Submit
from django import forms
from django.forms import ModelForm


class AwardForm(ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.layout = Layout(
            Row(
                Column(Field("decision"), css_class="form-group col-md-4 mb-1"),
                Column(Field("awarded"), css_class="form-group col-md-4 mb-1"),
                css_class="form-row",
            ),
            Row(
                Column(Field("comments"), css_class="form-group col-md-8 mb-1"),
                css_class="form-row",
            ),
            Row(
                Column(Field("acta"), css_class="form-group col-md-4 mb-1"),
                css_class="form-row",
            ),
            Row(
                Column("require_deliverable", css_class="form-group col-md-4 mb-1"),
                css_class="form-row",
            ),
            Row(
                Column("deliverable_by", css_class="form-group col-md-4 mb-1"),
                css_class="form-row",
            ),
            FormActions(
                Submit("save", "Guardar"),
            ),
        )

    class Meta:
        model = Award
        exclude = ("id", "username", "program", "validated", "deliverable", "deliverable_validated", "created_at", "updated_at")
        widgets = {
            "deliverable_by": forms.SelectDateWidget(
                years=range(datetime.now().year, datetime.now().year + 10, 1),
                attrs=({"style": "width: 33%; display: inline-block;"}),
            ),
        }

reviews/templates/application_award.html
{% extends "base.html" %}

{% load crispy_forms_tags %}

{% block content %}

    <div class="container">
        <div class="row justify-content-md-center mt-4" style="background-color:white;">
            <div class="col col-lg">
                <h2>Resultado final</h2><br>
                <p><strong>Programa: </strong>{{ programa }}</p>
                <p><strong>CURP: </strong>{{ curp }}</p>
                <p><strong>Folio: </strong>{{ folio }}</p><br>
            </div>
        </div>
    </div>


    <div class="container">
        <div class="row justify-content-md-center" style="background-color:white;">
            <div class="col col-lg">

                <form method="POST" action="" enctype="multipart/form-data">
                    {% csrf_token %}
                    {% crispy form %}
                </form>

            </div>
        </div>
    </div>


{% endblock %}

reviews/templates/applications_list.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% load crispy_forms_tags %}
{% load widget_tweaks %}
{% load static %}
{% load humanize %}

{% block content %}

    <div class="container">
        <div class="row justify-content-md-center my-4">
            <div class="col col-sm text-left font-italic" style="font-size: smaller;">
                <p>Inicio > Staff > Aplicaciones </p>
            </div>
        </div>
    </div>


        <div class="container">
        <div class="row justify-content-md-center my-4" style="background-color:white;">
            <div class="col">
                <form method="get">
                    <div class="form-row">
                        <div class="form-group col-sm-2 mb-0">
                            {{ filter.form.program|add_class:"form-control form-control-sm"|as_crispy_field }}
                        </div>
                        <div class="form-group col-sm-2.5 mb-0">
                            {{ filter.form.folio__icontains|add_class:"form-control form-control-sm"|as_crispy_field }}
                        </div>
                        <div class="form-group col-sm-2.5 mb-0">
                            {{ filter.form.username__username__icontains|add_class:"form-control form-control-sm"|as_crispy_field }}
                        </div>
                        <div class="form-group col-sm-2 mb-0">
                            {{ filter.form.current_stage|add_class:"form-control form-control-sm"|as_crispy_field }}
                        </div>
                        <div class="form-group col-sm-2 mb-0">
                            {{ filter.form.decision__decision|add_class:"form-control form-control-sm"|as_crispy_field }}
                        </div>
                        <div class="form-group col-sm-0.5 align-self-center text-right mb-0">
                            <button type="submit" class="btn btn-primary btn-sm">Filtrar</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>





    <div class="container">
        <div class="row justify-content-betweencontainer-sm my-4" style="background-color:white;">
            <div class="col col-lg my-4">
                <table class="table table-light small">
                    <div class="table-responsive">
                        <table class="table align-middle table-striped small" style="text-align:center">
                            <tr>
                                <th>Programa</th>
                                <th>Folio</th>
                                <th>CURP</th>
                                <th>Estatus</th>
                                <th>Puntuación</th>
                                <th>Decisión</th>
                                <th>Detalle</th>
                            </tr>
                            {% for application in object_list %}
                                <tr>
                                    <td>{{ application.program.title|title }}</td>
                                    <td>{{ application.folio|upper }}</td>
                                    <td>{{ application.username|upper }}</td>
                                    <td>{{ application.get_current_stage_display }}</td>
                                    <td>{{ application.score|default:"" }}</td>
                                    <td>{{ application.decision.get_decision_display }}</td>
                                    <td>
                                        <a type="button" class="btn btn-outline-primary btn-sm"
                                           href="{% url 'staff-application-review' application.id %}">
                                             <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-eyeglasses" viewBox="0 0 16 16">
                                              <path d="M4 6a2 2 0 1 1 0 4 2 2 0 0 1 0-4zm2.625.547a3 3 0 0 0-5.584.953H.5a.5.5 0 0 0 0 1h.541A3 3 0 0 0 7 8a1 1 0 0 1 2 0 3 3 0 0 0 5.959.5h.541a.5.5 0 0 0 0-1h-.541a3 3 0 0 0-5.584-.953A1.993 1.993 0 0 0 8 6c-.532 0-1.016.208-1.375.547zM14 8a2 2 0 1 1-4 0 2 2 0 0 1 4 0z"/>
                                            </svg>
                                        </a>
                                    </td>
                                </tr>
                            {% empty %}
                                <td>
                                    No hay registros.
                                </td>
                            {% endfor %}
                        </table>


                        <div class="pagination justify-content-center" style="border-bottom: #0b2e13">
                        <span class="step-links">
                            {% if page_obj.has_previous %}
                                <a class="previous round" href="?page=1">&laquo;</a>
                                <a class="previous round" href="?page={{ page_obj.previous_page_number }}">&#8249;</a>
                            {% endif %}

                            <span class="current">
                                Página {{ page_obj.number }} de {{ page_obj.paginator.num_pages }}
                            </span>

                            {% if page_obj.has_next %}
                                <a class="next round" href="?page={{ page_obj.next_page_number }}">&#8250;</a>
                                <a class="next round" href="?page={{ page_obj.paginator.num_pages }}">&raquo;</a>
                            {% endif %}
                        </span>
                        </div>
                    </div>
                </table>

            </div>
        </div>
    </div>

{% endblock %}

reviews/templates/awards_list.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% load crispy_forms_tags %}
{% load widget_tweaks %}
{% load static %}
{% load humanize %}

{% block content %}

    <div class="container">
        <div class="row justify-content-md-center my-4">
            <div class="col col-sm text-left font-italic" style="font-size: smaller;">
                <p>Inicio > Staff > Resultados y seguimiento </p>
            </div>
        </div>
    </div>


        <div class="container">
        <div class="row justify-content-md-center my-4" style="background-color:white;">
            <div class="col">
                <form method="get">
                    <div class="form-row">
                        <div class="form-group col-sm-2 mb-0">
                            {{ filter.form.program|add_class:"form-control form-control-sm"|as_crispy_field }}
                        </div>
                        <div class="form-group col-sm-2.5 mb-0">
                            {{ filter.form.username__username__icontains|add_class:"form-control form-control-sm"|as_crispy_field }}
                        </div>
                        <div class="form-group col-sm-2.5 mb-0">
                            {{ filter.form.deliverable_validated|add_class:"form-control form-control-sm"|as_crispy_field }}
                        </div>
                        <div class="form-group col-sm-2 mb-0">
                            {{ filter.form.award_delivered|add_class:"form-control form-control-sm"|as_crispy_field }}
                        </div>
                        <div class="form-group col-sm-2 mb-0">
                            {{ filter.form.decision|add_class:"form-control form-control-sm"|as_crispy_field }}
                        </div>
                        <div class="form-group col-sm-0.5 align-self-center text-right mb-0">
                            <button type="submit" class="btn btn-primary btn-sm">Filtrar</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>





    <div class="container">
        <div class="row justify-content-betweencontainer-sm my-4" style="background-color:white;">
            <div class="col col-lg my-4">
                <table class="table table-light small">
                    <div class="table-responsive">
                        <table class="table align-middle table-striped small" style="text-align:center">
                            <tr>
                                <th>Programa</th>
                                <th>CURP</th>
                                <th>Decisión</th>
                                <th>Monto</th>
                                <th>Estatus</th>
                                <th></th>
                                <th></th>
                            </tr>
                            {% for award in object_list %}
                                <tr>
                                    <td>{{ award.program.title|title }}</td>
                                    <td>{{ award.username|upper }}</td>
                                    <td>{{ award.get_decision_display }}</td>
                                    <td>{{ award.awarded|intcomma }}</td>
                                    <td>{{ award.id.get_current_stage_display }}</td>
                                    <td>
                                        <a type="button" class="btn btn-outline-secondary btn-sm"
                                           href="{% url 'staff-application-review' award.id.id %}">
                                             <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-eyeglasses" viewBox="0 0 16 16">
                                              <path d="M4 6a2 2 0 1 1 0 4 2 2 0 0 1 0-4zm2.625.547a3 3 0 0 0-5.584.953H.5a.5.5 0 0 0 0 1h.541A3 3 0 0 0 7 8a1 1 0 0 1 2 0 3 3 0 0 0 5.959.5h.541a.5.5 0 0 0 0-1h-.541a3 3 0 0 0-5.584-.953A1.993 1.993 0 0 0 8 6c-.532 0-1.016.208-1.375.547zM14 8a2 2 0 1 1-4 0 2 2 0 0 1 4 0z"/>
                                            </svg>
                                            Ver aplicación
                                        </a>
                                    </td>
                                    {% if not award.award_delivered %}
                                    <td>
                                        <button hx-get="{% url 'staff-deliver-award' award.id.id %}" hx-target="#withdraw" class="btn btn-outline-secondary btn-sm">
                                            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-pencil" viewBox="0 0 16 16">
                                              <path d="M12.146.146a.5.5 0 0 1 .708 0l3 3a.5.5 0 0 1 0 .708l-10 10a.5.5 0 0 1-.168.11l-5 2a.5.5 0 0 1-.65-.65l2-5a.5.5 0 0 1 .11-.168l10-10zM11.207 2.5 13.5 4.793 14.793 3.5 12.5 1.207 11.207 2.5zm1.586 3L10.5 3.207 4 9.707V10h.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.5h.293l6.5-6.5zm-9.761 5.175-.106.106-1.528 3.821 3.821-1.528.106-.106A.5.5 0 0 1 5 12.5V12h-.5a.5.5 0 0 1-.5-.5V11h-.5a.5.5 0 0 1-.468-.325z"/>
                                            </svg>
                                            Entregar apoyo
                                        </button>
                                    </td>
                                        {% elif award.require_deliverable and award.deliverable and not award.deliverable_validated %}
                                    <td>
                                        <button hx-get="{% url 'staff-validate-deliverable' award.id.id %}" hx-target="#withdraw" class="btn btn-outline-secondary btn-sm">
                                            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-pencil" viewBox="0 0 16 16">
                                              <path d="M12.146.146a.5.5 0 0 1 .708 0l3 3a.5.5 0 0 1 0 .708l-10 10a.5.5 0 0 1-.168.11l-5 2a.5.5 0 0 1-.65-.65l2-5a.5.5 0 0 1 .11-.168l10-10zM11.207 2.5 13.5 4.793 14.793 3.5 12.5 1.207 11.207 2.5zm1.586 3L10.5 3.207 4 9.707V10h.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.5h.293l6.5-6.5zm-9.761 5.175-.106.106-1.528 3.821 3.821-1.528.106-.106A.5.5 0 0 1 5 12.5V12h-.5a.5.5 0 0 1-.5-.5V11h-.5a.5.5 0 0 1-.468-.325z"/>
                                            </svg>
                                            Validar entregables
                                        </button>
                                    </td>
                                {% endif %}
                                </tr>
                            {% empty %}
                                <td>
                                    No hay registros.
                                </td>
                            {% endfor %}
                        </table>


                        <div class="pagination justify-content-center" style="border-bottom: #0b2e13">
                        <span class="step-links">
                            {% if page_obj.has_previous %}
                                <a class="previous round" href="?page=1">&laquo;</a>
                                <a class="previous round" href="?page={{ page_obj.previous_page_number }}">&#8249;</a>
                            {% endif %}

                            <span class="current">
                                Página {{ page_obj.number }} de {{ page_obj.paginator.num_pages }}
                            </span>

                            {% if page_obj.has_next %}
                                <a class="next round" href="?page={{ page_obj.next_page_number }}">&#8250;</a>
                                <a class="next round" href="?page={{ page_obj.paginator.num_pages }}">&raquo;</a>
                            {% endif %}
                        </span>
                        </div>
                    </div>
                </table>

            </div>
        </div>
    </div>

    <div id="modal-withdraw" class="modal fade">
        <div id="withdraw" class="modal-dialog" hx-target="this"></div>
    </div>

    <script src="{% static 'assets/js/other/modals.js' %}"></script>


{% endblock %}

reviews/templates/deliver_award.html
{% block content %}

    <form hx-post="{{ request.path }}" class="modal-content">
        {% csrf_token %}
        <div class="modal-header">
            <h5 class="modal-title">Confirmación de entrega de apoyo</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
        <div class="modal-body">
            <p>Confirme si entrego el apoyo al beneficiario.</p>
        </div>
        <div class="modal-footer">
            <button type="button" class="btn btn-outline-secondary btn-sm" data-dismiss="modal">Cancelar</button>
            <input type="submit" value="Confirmar" id="submit" name="submit"
                   class="btn btn-danger btn-sm">
        </div>
    </form>

{% endblock %}